name: 'Deploy'
 
on:
  push:
    branches:
    - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  terraform:
    name: 'Deploy'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_VAR_appId: ${{ secrets.AZURE_AD_CLIENT_ID }}
      TF_VAR_password: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      TF_ACTIONS_WORKING_DIR: "./terraform"

    runs-on: ubuntu-latest
    environment: demo
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform init

    - name: Terraform Validate
      id: validate
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform plan -no-color -out=tfplan
 
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      id: apply
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: terraform apply -no-color tfplan

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIAL }}

    - name: Get kubeconfig
      if: github.ref == 'refs/heads/master'
      id: kubeconfig
      working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
      run: |
        RG=$(echo '${{ steps.apply.outputs.stdout }}' | grep resource_group_name | cut -d'"' -f2')
        NAME=$(echo '${{ steps.apply.outputs.stdout }}' | grep kubernetes_cluster_name | cut -d'"' -f2')
        az aks get-credentials --resource-group ${RG} --name ${NAME} -f kubeconfig.cfg

    - uses: azure/setup-kubectl@v1
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: "terraform/kubeconfig.cfg"
    
    - name: Get Nodes
      if: github.ref == 'refs/heads/master'
      id: k_nodes
      run: kubectl get nodes