name: 'Destroy'
 
on: 
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      TF_ACTIONS_WORKING_DIR: "./terraform"

    runs-on: ubuntu-latest
    environment: production
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_ACTIONS_WORKING_DIR }}
 
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get SSH public key
      run: curl -s https://github.com/${{ github.event.repository.owner.name}}.keys | grep vKESkcuQ > ./id_rsa.pub

    - name: Get SSH private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./id_rsa; sed -i -e 's/^/     /' ./id_rsa; sed -i -e '/    content:/r ./id_rsa' ../scripts/bastion-cloud-init.txt

    - uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform destroy
      id: destroy
      run: terraform destroy -auto-approve -lock=false
    
    - run: echo ${{ steps.apply.destroy.stdout }}
    - run: echo ${{ steps.apply.destroy.stderr }}
    - run: echo ${{ steps.apply.destroy.exitcode }}